server:
  port: 8989

spring:
  application:
    name: done-with-bcknd
  profiles:
    active:
      - dev

# /api-docs endpoint custom path
#  springdoc.api-docs.path=/api-docs
springdoc:
  api-docs:
    path: /api-docs/**
  swagger-ui:
    path: /swagger-ui.html

file.local.path: images/
local.url: http://localhost:8989